/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipkkp.pendataan;

import Koneksi.koneksi;
import aplikasipkkp.Main;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author defam
 */
public class Pendataan extends javax.swing.JFrame {
    private DefaultTableModel DftTblModel_pendataan;
    private String SQL;
    /**
     * Creates new form Pendataan
     */
    public Pendataan() {
        initComponents();
        
        setResizable(false);
        
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendataan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pendataan Peserta");

        tblPendataan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPendataan);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Nama");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                            .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(688, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        String key=txtCari.getText();
        System.out.println(key);  
        
        if(key!=""){
            cariData(key);
        }else{
            tampilData();
        }
    }//GEN-LAST:event_txtCariKeyReleased

    public void tampilData(){
        DftTblModel_pendataan = new DefaultTableModel();
        DftTblModel_pendataan.addColumn("NIK");
        DftTblModel_pendataan.addColumn("Nama");
        DftTblModel_pendataan.addColumn("Tanggal Lahir");
        DftTblModel_pendataan.addColumn("Jenis Kelamin");
        DftTblModel_pendataan.addColumn("Kabupaten/Kota");
        DftTblModel_pendataan.addColumn("Kelurahan");
        DftTblModel_pendataan.addColumn("Kecamatan");
        tblPendataan.setModel(DftTblModel_pendataan);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from peserta";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_pendataan.addRow(new Object[]{
                    res.getString("nik"),
                    res.getString("nama"),
                    res.getString("tgl_lahir"),
                    res.getString("jenis_kelamin"),
                    res.getString("kota"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void cariData(String key){
        try{
            DftTblModel_pendataan = new DefaultTableModel();
            DftTblModel_pendataan.addColumn("NIK");
            DftTblModel_pendataan.addColumn("Nama");
            DftTblModel_pendataan.addColumn("Tanggal Lahir");
            DftTblModel_pendataan.addColumn("Jenis Kelamin");
            DftTblModel_pendataan.addColumn("Kabupaten/Kota");
            DftTblModel_pendataan.addColumn("Kelurahan");
            DftTblModel_pendataan.addColumn("Kecamatan");
            tblPendataan.setModel(DftTblModel_pendataan);
            
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            DftTblModel_pendataan.getDataVector().removeAllElements();
            
            SQL = "SELECT * from peserta WHERE nama LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
 
            while(res.next()){
                DftTblModel_pendataan.addRow(new Object[]{
                    res.getString("nik"),
                    res.getString("nama"),
                    res.getString("tgl_lahir"),
                    res.getString("jenis_kelamin"),
                    res.getString("kota"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }                
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendataan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
